// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-videos.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-videos.ts
var VIDEO_FIELDS = "id, title, description, category, source, duration, tags, thumbnail_url, embed_url, featured, views, created_at";
var search_videos_default = defineTool({
  name: "search_videos",
  title: "Search videos",
  description: "Search the public ClipFlow video catalog by keyword, category, source or featured flag. Returns matching videos ordered by newest first.",
  inputSchema: {
    query: z.string().trim().optional().describe("Keyword matched against video title and description."),
    category: z.string().trim().optional().describe("Category value, e.g. 'music' or 'sports'."),
    source: z.enum(["dailymotion", "rumble"]).optional().describe("Video source platform."),
    featured: z.boolean().optional().describe("Only return featured videos when true."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of videos to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, source, featured, limit }) => {
    const supabase = supabaseAnon();
    let request = supabase.from("videos").select(VIDEO_FIELDS).order("created_at", { ascending: false });
    if (query) request = request.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) request = request.eq("category", category);
    if (source) request = request.eq("source", source);
    if (featured !== void 0) request = request.eq("featured", featured);
    const { data, error } = await request.limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { videos: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-video.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_video_default = defineTool2({
  name: "get_video",
  title: "Get video",
  description: "Fetch full details for one public ClipFlow video by its id.",
  inputSchema: {
    id: z2.string().uuid().describe("The video id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("videos").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No video found with id ${id}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { video: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all public ClipFlow video categories with their labels, icons and slug values.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("categories").select("id, value, label, icon, sort_order").order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-playlists.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_playlists_default = defineTool4({
  name: "list_playlists",
  title: "List playlists",
  description: "List public ClipFlow playlists, optionally filtered by category.",
  inputSchema: {
    category: z3.string().trim().optional().describe("Category value to filter playlists by."),
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum number of playlists (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = supabaseAnon();
    let request = supabase.from("playlists").select("id, title, description, category, thumbnail_url, created_at").order("created_at", { ascending: false });
    if (category) request = request.eq("category", category);
    const { data, error } = await request.limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { playlists: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-playlist.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_playlist_default = defineTool5({
  name: "get_playlist",
  title: "Get playlist with videos",
  description: "Fetch one public ClipFlow playlist by id, including its ordered list of videos.",
  inputSchema: {
    id: z4.string().uuid().describe("The playlist id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = supabaseAnon();
    const { data: playlist, error } = await supabase.from("playlists").select("id, title, description, category, thumbnail_url, created_at").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!playlist) return { content: [{ type: "text", text: `No playlist found with id ${id}` }], isError: true };
    const { data: items, error: itemsError } = await supabase.from("playlist_videos").select("sort_order, videos(id, title, description, category, source, duration, thumbnail_url, embed_url, views)").eq("playlist_id", id).order("sort_order", { ascending: true });
    if (itemsError) return { content: [{ type: "text", text: itemsError.message }], isError: true };
    const videos = (items ?? []).map((item) => item.videos).filter(Boolean);
    const result = { ...playlist, videos };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { playlist: result }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "streamline-hub",
  title: "Streamline Hub",
  version: "0.1.0",
  instructions: "Read-only tools for the ClipFlow public video catalog. Use `search_videos` to find videos by keyword, category, source or featured flag, `get_video` for full details of one video, `list_categories` for available categories, and `list_playlists` / `get_playlist` to browse curated playlists.",
  tools: [search_videos_default, get_video_default, list_categories_default, list_playlists_default, get_playlist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
